apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: trunks
    tier: client
  name: trunks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trunks
      tier: client
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: trunks
        tier: client
    spec:
      containers:
      - env:
        - name: VEGETA_HOST
          value: a9481c0e0450411e7bfdd12dff68689d-1028345378.us-east-1.elb.amazonaws.com 
        image: registry.hub.docker.com/souranilsbu/trunks:latest
        name: trunks
        resources: {}
status: {}

