apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vegeta
    tier: frontend
  name: vegeta-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vegeta
      tier: frontend
  strategy:
    # indicate which strategy we want for rolling update
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vegeta
        tier: frontend
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        image: docker.io/souranilsbu/vegeta:latest
        name: vegeta-broker
        ports:
        - containerPort: 1337
        resources: {}
status: {}
