apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: vegeta
    tier: frontend
  name: vegeta-broker
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: vegeta
      tier: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: vegeta
        tier: frontend
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        image: registry.hub.docker.com/souranilsbu/vegeta
        name: vegeta-broker
        ports:
        - containerPort: 1337
        resources: {}
status: {}
